language: node_js
node_js:
- '8'
branches:
  only:
  - master
deploy:
  provider: npm
  email: hadaszeilberger@gmail.com
  api_key:
    secure: b10d4ed7-b340-4c0e-a3ad-46e03769dd41
  on:
    tags: true
